# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/martin/.local/lib/python3.8/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/martin/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/martin/Documents/skola/AVG/voronoi_raster

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/martin/Documents/skola/AVG/voronoi_raster

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/martin/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/martin/.local/lib/python3.8/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/martin/Documents/skola/AVG/voronoi_raster/CMakeFiles /home/martin/Documents/skola/AVG/voronoi_raster//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/martin/Documents/skola/AVG/voronoi_raster/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Voronizer

# Build rule for target.
Voronizer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Voronizer
.PHONY : Voronizer

# fast build rule for target.
Voronizer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voronizer.dir/build.make CMakeFiles/Voronizer.dir/build
.PHONY : Voronizer/fast

cpp/clustering.o: cpp/clustering.cpp.o
.PHONY : cpp/clustering.o

# target to build an object file
cpp/clustering.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voronizer.dir/build.make CMakeFiles/Voronizer.dir/cpp/clustering.cpp.o
.PHONY : cpp/clustering.cpp.o

cpp/clustering.i: cpp/clustering.cpp.i
.PHONY : cpp/clustering.i

# target to preprocess a source file
cpp/clustering.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voronizer.dir/build.make CMakeFiles/Voronizer.dir/cpp/clustering.cpp.i
.PHONY : cpp/clustering.cpp.i

cpp/clustering.s: cpp/clustering.cpp.s
.PHONY : cpp/clustering.s

# target to generate assembly for a file
cpp/clustering.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voronizer.dir/build.make CMakeFiles/Voronizer.dir/cpp/clustering.cpp.s
.PHONY : cpp/clustering.cpp.s

cpp/growing.o: cpp/growing.cpp.o
.PHONY : cpp/growing.o

# target to build an object file
cpp/growing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voronizer.dir/build.make CMakeFiles/Voronizer.dir/cpp/growing.cpp.o
.PHONY : cpp/growing.cpp.o

cpp/growing.i: cpp/growing.cpp.i
.PHONY : cpp/growing.i

# target to preprocess a source file
cpp/growing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voronizer.dir/build.make CMakeFiles/Voronizer.dir/cpp/growing.cpp.i
.PHONY : cpp/growing.cpp.i

cpp/growing.s: cpp/growing.cpp.s
.PHONY : cpp/growing.s

# target to generate assembly for a file
cpp/growing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voronizer.dir/build.make CMakeFiles/Voronizer.dir/cpp/growing.cpp.s
.PHONY : cpp/growing.cpp.s

cpp/main.o: cpp/main.cpp.o
.PHONY : cpp/main.o

# target to build an object file
cpp/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voronizer.dir/build.make CMakeFiles/Voronizer.dir/cpp/main.cpp.o
.PHONY : cpp/main.cpp.o

cpp/main.i: cpp/main.cpp.i
.PHONY : cpp/main.i

# target to preprocess a source file
cpp/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voronizer.dir/build.make CMakeFiles/Voronizer.dir/cpp/main.cpp.i
.PHONY : cpp/main.cpp.i

cpp/main.s: cpp/main.cpp.s
.PHONY : cpp/main.s

# target to generate assembly for a file
cpp/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voronizer.dir/build.make CMakeFiles/Voronizer.dir/cpp/main.cpp.s
.PHONY : cpp/main.cpp.s

cpp/utils.o: cpp/utils.cpp.o
.PHONY : cpp/utils.o

# target to build an object file
cpp/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voronizer.dir/build.make CMakeFiles/Voronizer.dir/cpp/utils.cpp.o
.PHONY : cpp/utils.cpp.o

cpp/utils.i: cpp/utils.cpp.i
.PHONY : cpp/utils.i

# target to preprocess a source file
cpp/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voronizer.dir/build.make CMakeFiles/Voronizer.dir/cpp/utils.cpp.i
.PHONY : cpp/utils.cpp.i

cpp/utils.s: cpp/utils.cpp.s
.PHONY : cpp/utils.s

# target to generate assembly for a file
cpp/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voronizer.dir/build.make CMakeFiles/Voronizer.dir/cpp/utils.cpp.s
.PHONY : cpp/utils.cpp.s

cpp/voronoi.o: cpp/voronoi.cpp.o
.PHONY : cpp/voronoi.o

# target to build an object file
cpp/voronoi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voronizer.dir/build.make CMakeFiles/Voronizer.dir/cpp/voronoi.cpp.o
.PHONY : cpp/voronoi.cpp.o

cpp/voronoi.i: cpp/voronoi.cpp.i
.PHONY : cpp/voronoi.i

# target to preprocess a source file
cpp/voronoi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voronizer.dir/build.make CMakeFiles/Voronizer.dir/cpp/voronoi.cpp.i
.PHONY : cpp/voronoi.cpp.i

cpp/voronoi.s: cpp/voronoi.cpp.s
.PHONY : cpp/voronoi.s

# target to generate assembly for a file
cpp/voronoi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voronizer.dir/build.make CMakeFiles/Voronizer.dir/cpp/voronoi.cpp.s
.PHONY : cpp/voronoi.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Voronizer"
	@echo "... cpp/clustering.o"
	@echo "... cpp/clustering.i"
	@echo "... cpp/clustering.s"
	@echo "... cpp/growing.o"
	@echo "... cpp/growing.i"
	@echo "... cpp/growing.s"
	@echo "... cpp/main.o"
	@echo "... cpp/main.i"
	@echo "... cpp/main.s"
	@echo "... cpp/utils.o"
	@echo "... cpp/utils.i"
	@echo "... cpp/utils.s"
	@echo "... cpp/voronoi.o"
	@echo "... cpp/voronoi.i"
	@echo "... cpp/voronoi.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

